openapi: 3.0.0
info:
  version: 1.0.0
  title: Money Mates API
servers:
  - url: 'https://example.com/api'

paths:
  /users:
    post:
      tags:
        - users
      summary: create-user-api
      description: This endpoint creates a new user in the system.
      parameters:
        - name: uuid
          in: header
          required: false
          description: uuid provided from auth server
          schema:
            type: string
            format: uuid
            example: "1a2b3c4d-5e6f-7g8h-9i0j-1k2l3m4n5o6p"

      requestBody:
        description: Body to be inserted
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateUserRequest'
            examples:
              Auth:
                $ref: '#/components/examples/CreateUserRequestAuthExample'
              NoAuth:
                $ref: '#/components/examples/CreateUserRequestNoAuthExample'
      responses:
        '201':
          description: A user is created successfully.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreateUserResponse'
              examples:
                Auth:
                  $ref: '#/components/examples/CreateUserResponseAuthExample'
                NoAuth:
                  $ref: '#/components/examples/CreateUserResponseNoAuthExample'

    patch:
      tags:
        - users
      summary: update-user-info-api
      description: This endpoint updates a user's email(for now)
      parameters:
        - $ref: '#/components/parameters/UuidHeader'

      requestBody:
        description: Body to be updated
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateUserInfoRequest'
            examples:
              regular:
                $ref: '#/components/examples/UpdateUserInfoRequestExample'
      responses:
        '200':
          description: A user is created successfully.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UpdateUserInfoResponse'
              examples:
                regular:
                  $ref: '#/components/examples/UpdateUserInfoResponseExample'

components:
  parameters:
    UuidHeader:
      name: uuid
      in: header
      required: true
      description: uuid provided from auth server
      schema:
        type: string
        format: uuid
        example: "1a2b3c4d-5e6f-7g8h-9i0j-1k2l3m4n5o6p"

  schemas:
    CreateUserRequest:
      $ref: '#/components/schemas/UserRequest'

    UpdateUserInfoRequest:
      $ref: '#/components/schemas/UserRequest'

    CreateUserResponse:
      $ref: '#/components/schemas/UserResponse'

    UpdateUserInfoResponse:
      $ref: '#/components/schemas/UserResponse'

    UserRequest:
      type: object
      required:
        - name
        - email
      properties:
        name:
          type: string
          description: User's name to be created
        email:
          type: string
          format: email
          description: User's email

    UserResponse:
      type: object
      required:
        - uuid
        - name
        - email
        - created_at
        - updated_at
      properties:
        uuid:
          type: string
          format: uuid
          description: User's UUID. Human readable.
        name:
          type: string
          description: User's name created
        email:
          type: string
          format: email
          description: User's email created
        created_at:
          type: string
          format: date-time
          description: Creation date.
        updated_at:
          type: string
          format: date-time
          description: Update date.

  examples:
    CreateUserRequestAuthExample:
      $ref: '#/components/examples/UserRequestAuthExample'

    CreateUserRequestNoAuthExample:
      $ref: '#/components/examples/UserRequestNoAuthExample'

    UpdateUserInfoRequestExample:
        $ref: '#/components/examples/UserRequestAuthExample'

    CreateUserResponseAuthExample:
      $ref: '#/components/examples/UserResponseAuthExample'

    CreateUserResponseNoAuthExample:
      $ref: '#/components/examples/UserResponseNoAuthExample'

    UpdateUserInfoResponseExample:
      $ref: '#/components/examples/UserResponseAuthExample'

    UserRequestAuthExample:
      value:
        user_name: "山田 花子"
        email: "hanako-yamada@gmail.com"

    UserRequestNoAuthExample:
      value:
        user_name: "山田 花子"
        email: ""

    UserResponseAuthExample:
      value:
        uuid: "1a2b3c4d-5e6f-7g8h-9i0j-1k2l3m4n5o6p"
        name: "山田 花子"
        email: "hanako-yamada@gmail.com"
        created_at: "2023-04-01T12:00:00+09:00"
        updated_at: "2023-04-01T12:00:00+09:00"

    UserResponseNoAuthExample:
      value:
        uuid: "1a2b3c4d-5e6f-7g8h-9i0j-1k2l3m4n5o6p"
        name: "山田 花子"
        email: ""
        created_at: "2023-04-01T12:00:00+09:00"
        updated_at: "2023-04-01T12:00:00+09:00"