openapi: 3.0.0
info:
  version: 1.0.0
  title: Money Mates API
servers:
  - url: 'https://example.com/api'

paths:
  /users:
    post:
      tags:
        - users
      summary: create-user-api
      description: This endpoint creates a new user in the system.
      parameters:
        - name: uuid
          in: header
          required: false
          description: uuid provided from auth server
          schema:
            type: string
            format: uuid
            example:  "1a2b3c4d-5e6f-7g8h-9i0j-1k2l3m4n5o6p"

      requestBody:
        description: Body to be inserted
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateUserRequest'
            examples:
              regular:
                $ref: '#/components/examples/CreateUserRequestExample'
      responses:
        '201':
          description: A user is created successfully.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreateUserResponse'
              examples:
                regular:
                  $ref: '#/components/examples/CreateUserResponseExample'

components:
  schemas:
    CreateUserRequest:
      type: object
      required:
        - user_name
      properties:
        user_name:
          type: string
          description: User's name to be created
        email:
          type: string
          format: email
          description: User's email

    CreateUserResponse:
      type: object
      required:
        - uuid
        - name
        - email
        - created_at
        - updated_at
      properties:
        uuid:
          type: string
          format: uuid
          description: User's UUID. Human readable.
        name:
          type: string
          description: User's name created
        email:
          type: string
          format: email
          description: User's email created
        created_at:
          type: string
          format: date-time
          description: Creation date.
        updated_at:
          type: string
          format: date-time
          description: Update date.

  examples:
    CreateUserRequestExample:
      value:
        user_name: "山田 花子"
        email: "hanako-yamada@gmail.com"

    CreateUserResponseExample:
      value:
        uuid: "1a2b3c4d-5e6f-7g8h-9i0j-1k2l3m4n5o6p"
        name: "山田 花子"
        email: "hanako-yamada@gmail.com"
        created_at: "2023-04-01T12:00:00+09:00"
        updated_at: "2023-04-01T12:00:00+09:00"