FirebaseAuth:
  type: http
  scheme: bearer
  bearerFormat: JWT
  description: Firebase Authentication JWT token for iOS clients

ApiKeyAuth:
  type: apiKey
  in: header
  name: X-API-KEY
  description: API Key authentication for Lambda system calls