name: Deploy OpenAPI Documentation

on:
  push:
    branches:
      - main  # メインブランチにプッシュされたときに実行

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.KEY_FOR_ELASTIC_COMPUTE_CLOUD }}

    - name: Deploy to EC2
      run: |
        rsync -avz --delete --include '*/' --include '*.yaml' --exclude '*' -e "ssh -o StrictHostKeyChecking=no" ./dist/ ec2-user@ec2-13-230-174-230.ap-northeast-1.compute.amazonaws.com:/home/ec2-user/money-me-openapi-spec/dist/